runtime: python313 # 您可以选择 python38, python39, python310 等
instance_class: F1 # 这是免费额度中最小也是最经济的实例类型

# Gunicorn是生产级的WSGI服务器，用于运行您的Flask应用
# :$PORT 是App Engine自动设置的环境变量
entrypoint: gunicorn -b :$PORT 'app:create_app()'

env_variables:
  # 在下一部分设置Cloud SQL时，您会得到这个连接名
  INSTANCE_CONNECTION_NAME: "ambient-decoder-467517-h8:northamerica-northeast1:cell-storage-instance"
  DB_USER: "postgres"
  DB_PASS: "Lqy960311!"
  DB_NAME: "postgres"
  SECRET_KEY: "^S3!bR7bk4i^#yYnly9f4LwPJ!K1FlUk" # 例如，使用 `openssl rand -hex 32` 生成
  
  # Centralized Printing Configuration
  CENTRALIZED_PRINTING_ENABLED: "true"